src/components/ac-map-layer-provider/ac-map-layer-provider.component.ts
src/main.ts
src/pipes/pixel-offset/pixel-offset.pipe.ts
src/services/coordinate-converter/coordinate-converter.service.ts
src/services/drawers/arc-drawer/arc-drawer.service.ts
src/services/drawers/billboard-drawer/billboard-drawer.service.ts
src/services/drawers/dynamic-polyline-drawer/dynamic-polyline-drawer.service.ts
src/services/drawers/ellipse-drawer/dynamic-ellipse-drawer.service.ts
src/services/drawers/ellipse-drawer/ellipse-drawer.service.ts
src/services/drawers/label-drawer/label-drawer.service.ts
src/services/drawers/point-drawer/point-drawer.service.ts
src/services/drawers/polygon-drawer/polygon-drawer.service.ts
src/services/drawers/static-circle-drawer/static-circle-drawer.service.ts
src/services/drawers/static-polyline-drawer/static-polyline-drawer.service.ts
src/services/drawers/static-primitive-drawer/static-primitive-drawer.service.ts
src/services/geo-utils/geo-utils.service.ts
src/services/map-events-mananger/consts/cesium-event-modifier.enum.ts
src/services/map-events-mananger/consts/cesium-event.enum.ts
src/services/viewer-factory/viewer-factory.service.ts
src/typings.d.ts
tsconfig.aot.json
tsconfig.json

add typings.d.ts for aot bundle compilation

remove declare var cesium

---

src/components/ac-layer/ac-layer.component.ts
src/components/ac-map-layer-provider/ac-map-layer-provider.component.ts

added show input to ac-map-provider

added onDestroy to ac-layer && ac-map-provider

---

demo/app/layers/base-layer/base-layer.component.html
demo/app/layers/base-layer/base-layer.component.ts
src/services/drawers/simple-drawer/simple-drawer.service.ts

if layer show is false then use layer show=false value, otherwise use primitive.show value .
resolve #44

layer show priority fix 

---

demo/utils/services/dataProvider/real-tracks-data-provider.ts

must create new watchQuery because when apollo client gets an error it
can not continue polling

demo - reconnect on error

---

src/components/ac-html/ac-html.component.ts

Fixed ac-html bad behavior

---

demo/app/components/demo-map/demo-map.component.html
demo/app/services/app-settings-service/app-settings-service.ts
demo/app/shared/settings-form/settings-form.component.html
src/angular-cesium.module.ts
src/components/ac-3d-tileset/ac-tileset-3d.component.ts
yarn.lock

feature(3d-tiles): added support for 3d tileset layer

---

src/services/viewer-configuration/viewer-configuration.service.ts

Fix comment in viewer-configuration.service.ts

Fix viewerConf

---

CHANGELOG.md
demo/app/components/event-test-layer/event-test-layer.component.ts
src/services/camera/camera.service.ts

added functionality to camera service

---

README.md

- line 163
- 'consits' => 'consists'

CHORE: spelling

---

CHANGELOG.md
src/angular-cesium/components/ac-map/ac-map.component.ts
src/angular-cesium/services/plonter/plonter.service.ts

Fix/init services order 

---

CHANGELOG.md
demo/app/components/polygon-layer/polygon-layer.component.html
demo/app/components/polygon-layer/polygon-layer.component.ts
src/angular-cesium/services/drawers/entities-drawer/entities-drawer.service.ts

updated changelog
updated polygon-layer in demo

fixed entities-drawer-service show prop bug

---

CHANGELOG.md
demo/app/components/demo-map/demo-map.component.html
src/angular-cesium-entities-editor/components/polylines-editor/polylines-editor.component.ts
src/angular-cesium-entities-editor/models/editable-polyline.ts
src/angular-cesium-entities-editor/models/hippodrome-editor-oboservable.ts
src/angular-cesium/models.ts
src/angular-cesium/models/cartesian2.ts
src/angular-cesium/models/cartesian3.ts
src/angular-cesium/services/coordinate-converter/coordinate-converter.service.ts
src/cesium-extender/primitives/html.ts
src/typings/cesium/index.d.ts

Edited Polyline virtual points fix

---

CHANGELOG.md
src/cesium-extender/primitives/html.ts

fix html primitive screen position to cesium cartesian 2

---

CHANGELOG.md
demo/app/components/toolbar-example/toolbar-example.component.ts

Fix range and bearing example 

---

CHANGELOG.md
src/angular-cesium/services/drawers/entities-drawer/entities-drawer.service.ts

fixed aot warning

---

CHANGELOG.md
demo/app/components/editor-layer/circles-editor-layer/circles-editor-layer.component.css
demo/app/components/editor-layer/hippodrome-example/hippodrome-editor-layer.component.css
demo/app/components/editor-layer/polygons-editor-layer/polygons-editor-layer.component.css
demo/app/components/event-test-layer/event-test-layer.component.ts
demo/app/components/layer-order/layer-order.component.ts
src/angular-cesium-widgets/models/label-props.ts
src/angular-cesium-widgets/services/entity-editors/circles-editor/circles-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/hippodrome-editor/hippodrome-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/polygons-editor/polygons-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/polyline-editor/polylines-editor.service.ts
src/angular-cesium/services/map-events-mananger/event-registration-input.ts
src/angular-cesium/services/map-events-mananger/map-events-manager.ts

Feature/version 0.0.41

---

CHANGELOG.md
demo/app/components/editor-layer/circles-editor-layer/circles-editor-layer.component.ts
demo/app/components/editor-layer/hippodrome-example/hippodrome-editor-layer.component.ts
demo/app/components/editor-layer/polygons-editor-layer/polygons-editor-layer.component.ts
demo/app/components/editor-layer/polyline-example/polyline-editor-layer.component.ts
package.json
src/angular-cesium-widgets/components/circles-editor/circles-editor.component.html
src/angular-cesium-widgets/components/circles-editor/circles-editor.component.ts
src/angular-cesium-widgets/components/hippodrome-editor/hippodrome-editor.component.html
src/angular-cesium-widgets/components/hippodrome-editor/hippodrome-editor.component.ts
src/angular-cesium-widgets/components/polygons-editor/polygons-editor.component.html
src/angular-cesium-widgets/components/polygons-editor/polygons-editor.component.ts
src/angular-cesium-widgets/components/polylines-editor/polylines-editor.component.html
src/angular-cesium-widgets/components/polylines-editor/polylines-editor.component.ts
src/angular-cesium-widgets/models/editable-hippodrome.ts
src/angular-cesium-widgets/services.ts
src/angular-cesium-widgets/services/entity-editors/circles-editor/circles-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/hippodrome-editor/hippodrome-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/polygons-editor/polygons-editor.service.ts
src/angular-cesium-widgets/services/entity-editors/polyline-editor/polylines-editor.service.ts
src/angular-cesium-widgets/services/utils.ts
src/angular-cesium/components/ac-array-desc/ac-array-desc.component.ts
src/angular-cesium/components/ac-layer/ac-layer.component.ts
src/angular-cesium/services/drawers/ellipse-drawer/ellipse-drawer.service.ts
src/angular-cesium/services/drawers/entities-drawer/entities-drawer.service.ts
src/angular-cesium/services/map-events-mananger/map-events-manager.ts
yarn.lock

Feature/version 0.0.43

---

CHANGELOG.md
src/angular-cesium-widgets/components/toolbar/ac-toolbar/ac-toolbar.component.ts

Fix ac-toolbar onDestory() 

---

src/angular-cesium/angular-cesium.module.ts
src/angular-cesium/cesium-enhancements/ConfigurationService.ts

fix(config): change 'config' token from string to InjectionToken

---

README.md

Fixing a few typos in the readme

fixing typos in readme

---

projects/angular-cesium/src/lib/angular-cesium/components/ac-map/ac-map.component.ts

found a typo on line 192 - 
serivce instead of service.

typo on line 192 - serivce instead of service

---

CHANGELOG.md
projects/angular-cesium/package.json
projects/angular-cesium/src/lib/angular-cesium-widgets/components/toolbar/ac-toolbar/ac-toolbar.component.ts

#247 
- [X ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ X] Make sure all changes are documented in CHANGESLOG.md and README.md

#247 - Add dragging hook and alter component to dynamically switch between static and draggable states

---

CHANGELOG.md
projects/angular-cesium/package.json
projects/angular-cesium/src/lib/angular-cesium/services/drawers/entities-drawer/entities-drawer.service.ts

This is for #187 
Pretty self-explanatory! I removed a line of unused code as well.
- [ :ballot_box_with_check:  ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ :ballot_box_with_check:  ] Make sure all changes are documented in CHANGESLOG.md and README.md
Thanks again for the awesome library @eitanfr !

Add use of 'availability' prop inside of Cesium entities

---

CHANGELOG.md
projects/angular-cesium/src/lib/angular-cesium/angular-cesium.module.ts

fix forRoot dependencies

---

CHANGELOG.md
demo/app/components/html-layer/html-example.component.html
demo/app/components/html-layer/html-example.component.ts
projects/angular-cesium/src/lib/angular-cesium/directives/ac-html/ac-html.directive.ts

fix ac-html show bug - created multiple html elements
Fixes #306

Fix ac-html show bug - created multiple html elements

---

projects/angular-cesium/src/lib/angular-cesium-widgets/services/entity-editors/ellipses-editor/ellipses-editor.service.ts

fixed https://github.com/articodeltd/angular-cesium/issues/338

Fixed EllipseEditorObservable Disposing

---

CHANGELOG.md
projects/angular-cesium/src/lib/angular-cesium-widgets/components/rectangles-editor/rectangles-editor.component.ts
projects/demo/src/app/app.module.ts
projects/demo/src/app/components/demo-map/demo-map.component.html
projects/demo/src/app/components/editor-layer/rectangle-editor-example/rectangle-editor-example.component.css
projects/demo/src/app/components/editor-layer/rectangle-editor-example/rectangle-editor-example.component.html
projects/demo/src/app/components/editor-layer/rectangle-editor-example/rectangle-editor-example.component.ts

fix rectangle edit

---

CHANGELOG.md
README.md
projects/angular-cesium/src/lib/angular-cesium/components/ac-map-layer-provider/ac-map-layer-provider.component.ts
projects/angular-cesium/src/lib/angular-cesium/models/map-layer-provider-options.enum.ts
projects/demo/src/app/components/demo-map/demo-map.component.html
projects/demo/src/app/components/demo-map/demo-map.component.ts

Request to merge in changes to angular-cesium MapLayerProviderOptions enum - with added Mapbox styles support
